apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: prometheus-certificate
  namespace: default
spec:
  secretName: prometheus-certs
  issuerRef:
    name: letsencrypt-prod-cluster-issuer
    kind: ClusterIssuer
  commonName: prometheus.wordnet.world
  dnsNames:
  - prometheus.wordnet.world
  acme:
    config:
    - http01:
        ingressClass: traefik
      domains:
      - prometheus.wordnet.world
