apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: wordnet-world-web-app
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wordnet-world-web-app
    spec:
      containers:
      - image: cjblink1/wordnet-world-web-app:ec6141c62d8289bca28d73d02626f25850ca87fc
        name: wordnet-world-web-app
        ports:
        - containerPort: 80
        resources: {}
status: {}
