apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: wordnet-world-web-app
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wordnet-world-web-app
    spec:
      containers:
      - image: cjblink1/wordnet-world-web-app:bd4e98e1ef918bdcade5667b93a732eaba43d2c8
        name: wordnet-world-web-app
        ports:
        - containerPort: 80
        resources: {}
status: {}
