apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: wordnet-world-web-app
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wordnet-world-web-app
    spec:
      containers:
      - image: cjblink1/wordnet-world-web-app:4c8818c46e12f56897a79e99b1c0bbd89eb13fac
        name: wordnet-world-web-app
        ports:
        - containerPort: 80
        resources: {}
status: {}
