apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordnet-world-web-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wordnet-world-web-app
    spec:
      containers:
        - name: wordnet-world-web-app
          image: 'cjblink1/wordnet-world-web-app:66a9d802383db140be9c34de1c41eb9e81777c10'
          ports:
            - containerPort: 80
