apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: wordnet-world-conductor
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wordnet-world-conductor
    spec:
      containers:
      - env:
        - name: STAGE
          value: "true"
        image: cjblink1/wordnet-world-conductor:66a347eff6bd2ff184b405cacef0e2f4cf7b8b49
        name: wordnet-world-conductor
        ports:
        - containerPort: 8675
        resources: {}
        volumeMounts:
        - mountPath: /go/src/github.com/wordnet-world/Conductor/config/
          name: config
          readOnly: true
      volumes:
      - name: config
        secret:
          secretName: conductor-conf
status: {}
