apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: wordnet-world-web-app
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wordnet-world-web-app
    spec:
      containers:
      - image: cjblink1/wordnet-world-web-app:28963ea505a95a9f3230a257e6287eabe6634c7d
        name: wordnet-world-web-app
        ports:
        - containerPort: 80
        resources: {}
status: {}
