apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: wordnet-world-web-app
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wordnet-world-web-app
    spec:
      containers:
      - image: cjblink1/wordnet-world-web-app:f32436543275a13bb7ebabcdc0e19279f9ab4aa1
        name: wordnet-world-web-app
        ports:
        - containerPort: 80
        resources: {}
status: {}
