apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: wordnet-world-web-app
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wordnet-world-web-app
    spec:
      containers:
      - image: cjblink1/wordnet-world-web-app:fd72c9e02ea74e1f9ee80b321dfc61fc6b7a5cc8
        name: wordnet-world-web-app
        ports:
        - containerPort: 80
        resources: {}
status: {}
