apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: wordnet-world-web-app
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wordnet-world-web-app
    spec:
      containers:
      - image: cjblink1/wordnet-world-web-app:c99e178dcc1012e09abe37d928f0d2ba1e508bee
        name: wordnet-world-web-app
        ports:
        - containerPort: 80
        resources: {}
status: {}
