apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wordnet-world
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/custom-response-headers: "Access-Control-Allow-Origin: *"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
#     traefik.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: wordnet.world
    http:
      paths:
      - path: /api
        backend:
          serviceName: wordnet-world-conductor
          servicePort: 80
      - path: /
        backend:
          serviceName: wordnet-world-web-app
          servicePort: 80
  tls:
  - secretName: wordnet-world-certs
