
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: wordnet-world-certificate
  namespace: default
spec:
  secretName: wordnet-world-certs
  issuerRef:
    name: letsencrypt-prod-cluster-issuer
    kind: ClusterIssuer
  commonName: wordnet.world
  dnsNames:
  - wordnet.world
  acme:
    config:
    - http01:
        ingressClass: traefik
      domains:
      - wordnet.world
